atomicals/atomicals-js

lib/cli.ts

fix bug: address not found when run "yarn cli address bc1pxxxxx"

Update cli.ts to fix an address undefined bug when run "yarn cli address" 

---

lib/commands/wallet-import-command.ts
lib/commands/wallet-init-command.ts
lib/utils/validate-wallet-storage.ts

Add an optional `WALLET_PATH` env, thus we can manage multiple wallets easily.
The `cli` commands will be this:
```bash
WALLET_PATH=path-to-wallet.json yarn cli [commands]
```

add WALLET_PATH env

---

lib/cli.ts
lib/commands/mint-interactive-subrealm-direct-command.ts
lib/commands/wallet-init-command.ts
lib/index.ts
lib/utils/atomical-operation-builder.ts
lib/utils/create-key-pair.ts
package.json

Critical update:
Add phrase and path options to wallet-init. 
Fix subrealm mint to not send parent

Add phrase and path options to wallet-init. Fix subrealm mint to not send parent

---

lib/commands/command-helpers.ts

...instead of the incorrect implementation across platforms.

Use standardized `basename` for commands

---

lib/utils/atomical-format-helpers.ts

Base on https://www.crockford.com/base32.html, fixed Crockford's Base32 alphabet, remove character 'u'.

fixed Crockford's Base32 alphabet, remove character 'u'.

---

lib/utils/atomical-operation-builder.ts

Output `nonce` and `time` are different from the actual bitworking matrixes previously, which makes the process unrecoverable.

🐛 Fix incorrect nonce and time logs

---

lib/api/electrum-api.ts

Exception from `getUnspentAddress` will completely break the minting process. It's uncoverable.

🥅 Do not throw exception if `getUnspentAddress` throws

---

lib/cli.ts

There's a parameter in find-containers command never used, --q and --asc can not accept by options

Remove unused cli command parameter

---

lib/api/electrum-api.interface.ts
lib/api/electrum-api.ts

- Sort UTXOs in asc, use the smallest UTXO first.
- Allow `usePost` argument in `ElectrumApi.createClient`.

Multiple improvements to the `ElectrumApi`

---

lib/commands/create-dmint-command.ts
lib/commands/create-dmint-manifest-command.ts

Consider the folder contains `.DS_Store` on macOS. The change skips all hidden files (starts with `.`).

🔥 Skip files starts with `.` rather than only `.`/`..`

---

lib/commands/broadcast-command.ts
lib/commands/get-container-item-validated-by-manifest-command.ts
lib/commands/mint-interactive-ditem-command.ts

When commands are returned with results, some do not follow `{success: true, data: result}` structure, which produces `undefined` logging, e.g. `mint-item` and `broadcast`.
https://github.com/atomicals/atomicals-js/blob/80cd7b8ed14bcfa49b099c646fa8df7feb4a66d4/lib/cli.ts#L23-L28

🐛 Fix wrong structure in returning results

---

lib/types/UTXO.interface.ts
lib/utils/select-funding-utxo.ts

`getInputUtxoFromTxid` seems not in use, but a hack with bracket notation to avoid type warning could be a foot gun one day.
- Enhance the type security to use `UXTO` from type definition. update UXTO type to have `nonWitnessUtxo?: Buffer;`
- Remove unused var and import
- Change `bitcoin-js` import to be module import

enhance type secure in select-funding-utxo

---

.env.example
README.md
lib/utils/atomical-operation-builder.ts

This commit introduces the CONCURRENCY parameter in the .env file, allowing users to specify the number of concurrent processes. This enhancement provides better control over resource usage, especially on systems with multiple CPU cores. The functionality defaults to using all available CPU cores minus one if CONCURRENCY is not explicitly set. This update includes modifications in the code to handle this new configuration and updates to the README for clear guidance.

Add optional CONCURRENCY parameter in .env for process control

---

lib/utils/select-funding-utxo.ts

refactor: use `const` to define no changed variables
simplify `filter` logic, clean code

refactor: use `const` to define no changed variables

---

lib/cli.ts

The `type` arg passed into `showWalletDetails` not in use, it will always show both `ft` and `nft` atomicals.
A type filter could be very useful for user who rely on cli to display their large amount of atomicals. Implement the functionality for summary only output.
Highlighted it's not compatible with `showExtra`, `showBalancesOnly`

Implement type filter for show wallet detail

---

lib/api/electrum-api.ts

Hey team,
I noticed that we're not updating the isOpenFlag property in the open() / close() method. What this means is that even if you call open(), the isOpen() method will still think we're not connected and return false.
Fix:
1. Updating the isOpenFlag property in the open() / close() / resetConnection() method
2. Adding async keyword

Update the isOpenFlag property

---

lib/utils/atomical-operation-builder.ts

When mint `quark`, I found that with default concurrency (cpus-1):
- `CPU Usage` is about 60-70%.
- `LOAD` is half of the cpu cores.
Aasked some of my friends, they met same problem.
Maybe we can cancel the max limit of `CONCURRENCY`. Let users choose by themselves.

chore: CONCURRENCY can be gt CPU cores

---

lib/utils/address-helpers.ts

The logic for converting an address to an output script and then to a script hash is repeated multiple times. It would be good to refactor into a separate function to reduce code duplication.

Refactor detectAddressTypeToScripthash

---

lib/utils/atomical-format-helpers.ts

Update the isAtomicalId function to enhance its validation process and ensure a return value is included in the catch block.

Update validation of isAtomicalId function 

---

lib/cli.ts

always exit with exit code 0 is unfriendly to other external programs.
we need to exit with a non-0 exit code when the result is failure.

exit with a non-0 exit code when the result is failure

---

lib/utils/atomical-operation-builder.ts

Sometimes reveal transaction couldn't broadcast because of rpc error, user can not broadcast manually.

Print reveal raw tx after mining succeed

---

.env
lib/api/electrum-api.ts

This pr added support for setting multiple endpoints with comma `,` in `.env` file.
`ELECTRUMX_PROXY_BASE_URL=https://ep.atomicalmarket.com/proxy,https://ep.atomicals.xyz/proxy`
And after failing to call one of the endpoints, will retry for another one. This is useful when one endpoint always returns `500` or `503` with a high server load.
Also, we can implement a client-side load balancer in the future

feat: support multiple electrum endpoints

---

lib/cli.ts
lib/index.ts

- Some commands only use an address but call `resolveWalletAliasNew` to resolve a wallet record, such as `mint-dft`, preventing users from inputting another wallet address to receive Atomicals.
- Promote `resolveAddress` type definition to avoid `any` calls.

🚀 Use `resolveAddress` as much as possible

---

lib/utils/atomical-operation-builder.ts

- Raise the excessive fee from `500000` to `1000000`.
- Prompt when hitting the limit rather than aborting the process to avoid BTC loss in the reveal wallet account.

🚸 Prompt for excessive fee instead of abort

---

README.md

This pr fixes some grammar of `README.md`, and merges  `Explore the CLI` and `Quick Commands` descriptions

refactor: improve README.md

---

lib/utils/miner-worker.ts

We ([PoW Lab](https://twitter.com/pow_lab)) are dedicated to promoting Proof of Work (PoW) consensus and firmly believe that PoW consensus is the fairest game in the blockchain space. We appreciate the Atomicals project but have identified several issues in this project (atomicals-js) that affect mining hash rates. Therefore, we have decided to optimize the open-source code through our efforts to ensure that everyone can achieve high hash rates. This is the first in our series of PRs.
Firstly, we added a [commit](https://github.com/atomicals/atomicals-js/commit/4996dca39334874c45670fa8f545a39bd0c5d2b5) that outputs hash rates every 10,000 hashes. The purpose is to quantify hash rates more clearly for subsequent optimizations.
Then, in this …

[PoW Lab] Enhance hash rate 5x by reducing the use of  `await sleep(0)`.

---

lib/utils/miner-worker.ts

We ([PoW Lab](https://twitter.com/pow_lab)) are dedicated to promoting Proof of Work (PoW) consensus and firmly believe that PoW consensus is the fairest game in the blockchain space.
During our process of optimizing the hash rate for atomicals-js, we discovered a serious issue that could potentially result in bitworkc lengths greater than 8 bits never being mined.
In https://github.com/atomicals/atomicals-js/pull/156, each worker is responsible for computing a portion of the range from 0 to MAX_SEQUENCE. For instance, if there are N workers, then they each handle ranges like 0 to 1/N*MAX_SEQUENCE, 1/N*MAX_SEQUENCE to 2/N*MAX_SEQUENCE, and so on. Due to a bug in [this code](https://github.com/NeutronProtocol/atomicals-js/blob/644b8de7d20c630176272334c27810e4d093fb3a/lib/utils/miner-worker. …

[PoW Lab] Fix an issue that bitworkc lengths greater than 8 bits may never being mined

---

lib/cli.ts

During deployment, uppercase letters are supported, but when using the 'get' command, it cannot be found with uppercase letters; you need to use lowercase letters.

fix yarn cli get command caseinsensitive

---

lib/commands/get-container-item-validated-by-manifest-command.ts

Displays errors which would help to determine the container status before it hits validation failure.

🚸 Log container error status while validating

---

lib/commands/mint-interactive-subrealm-command.ts
lib/commands/mint-interactive-subrealm-direct-command.ts
lib/commands/mint-interactive-subrealm-with-rules-command.ts

The previous condition check is reversed which makes the nearest Realm check invalid.

🐛 Fix invalid nearest Realm parent check when minting Sub-Realm

---

lib/commands/command-helpers.ts

Commands like `validate-container-item` will request the status of the container and the item. If they are pending, an unrelated status will be thrown, confusing users.

🚸 Tell the pending status before reading the result

---

lib/utils/miner-worker.ts
package.json
patches/bitcoinjs-lib+6.1.3.patch
yarn.lock

We ([PoW Lab](https://twitter.com/pow_lab)) are dedicated to promoting the Proof of Work (PoW) consensus and firmly believe that PoW consensus is the fairest game in the blockchain space. While we appreciate the Atomicals project, we have identified several issues in this project (atomicals-js) that affect mining hash rates. Therefore, we have decided to optimize the open-source code through our efforts to ensure that everyone can achieve high hash rates.
In this pull request, we refactored the miner worker to skip the signing of bitwork mining. This decision is based on a reasonable assumption: for PSBT, whether signed or not, it will not affect its transaction ID. This assumption is easily verifiable, and we won't elaborate on it here.
To achieve this goal, we need to make some …

[PoW Lab] Enhance hash rate 5x by skipping the signing of bitwork mining
