lib/commands/merge-interactive-utxos.ts
seperate -> separate
seperated -> separated
=> Fix typo in merge-interactive-utxos.ts

.env, .env.example, README.md, lib/commands/wallet-import-command.ts, lib/commands/wallet-init-command.ts, lib/utils/validate-wallet-storage.ts, lib/utils/wallet-path-resolver.ts, package.json
WALLET_PATH 
WALLET_FILE
environment variables added to allow configuration of the location of the wallet file and path.
=> Add configurable wallet path

.env, .env.example, lib/cli.ts, lib/commands/command-helpers.ts, lib/commands/init-interactive-dft-command.ts, lib/commands/merge-interactive-utxos.ts, lib/commands/mint-interactive-ft-command.ts, lib/commands/transfer-interactive-nft-command.ts, lib/commands/transfer-interactive-utxos-command.ts, lib/commands/wallet-import-command.ts, lib/utils/address-helpers.ts, lib/utils/address-keypair-path.ts, lib/utils/create-key-pair.ts, lib/utils/decode-mnemonic-phrase.ts, lib/utils/validate-wallet-storage.ts, package.json
=> Add testnet capabilities

container-dmint-guide.md, lib/cli.ts, lib/commands/command-helpers.ts, lib/commands/enable-subrealm-rules-command.ts, lib/commands/prepare-dmint-interactive-command.ts, lib/commands/prepare-dmint-items-interactive-command.ts, lib/commands/set-container-data-interactive-command.ts, lib/index.ts, lib/interfaces/api.interface.ts, lib/utils/atomical-format-helpers.ts, package.json
Add new commands for decentralized mint (dmint)
```
yarn cli prepare-dmint-manifest ./dmint chunks
yarn cli prepare-dmint-items mycoolcontainername ./chunks0.json --satsbyte=10
yarn cli prepare-dmint-config mycoolcontainername 812000 
```
=> Prepare dmint config commands

lib/commands/command-helpers.ts
...in order to let users know the Atomical is not under any address anymore.
=> Raise a better exception when the location is invalid

.env.example, lib/commands/command-helpers.ts, lib/utils/address-helpers.ts
=> feat: run cli with regtest

lib/cli.ts, lib/commands/split-interactive-command.ts, lib/commands/transfer-interactive-ft-command.ts, lib/commands/transfer-interactive-nft-command.ts, lib/commands/transfer-interactive-utxos-command.ts, lib/utils/atomical-format-helpers.ts
fix typo: seperate -> separate
=> chore: fix typos

package.json, yarn.lock
To resolve `critical` vulnerability https://github.com/lucky2077/atomicals-js/security/dependabot/49
=> upgrade crypto-js to 4.2.0

lib/utils/atomical-operation-builder.ts, templates/fungible-tokens/full-ft-meta.json
Hi there I'm reading the code and find comments are not correct.
=> Fix some comment errors

lib/commands/mint-interactive-ditem-command.ts
Prevent minting if an item is: (🆕 requesting, ✅ implemented)
- 🆕 Not proof valid
- ✅ Already claimed
- 🆕 Already has status
- ✅ No valid applicable mint rule
- ✅ Dismatched bitwork
=> 🚑️ Check DMINT item status before start mint

lib/utils/atomical-operation-builder.ts, lib/utils/miner-worker.ts, package.json
Feature by: https://github.com/danieleth2/atomicals-js
Copied from: https://github.com/danieleth2/atomicals-js/commit/02e854cc71c0f6c6559ff35c2093dc8d526b5d72
=> Multi-threaded Bitwork Mining - Credit to danieleth2

lib/utils/create-key-pair.ts, lib/utils/create-mnemonic-phrase.ts, lib/utils/file-utils.ts, lib/utils/select-funding-utxo.ts, lib/utils/utils.ts
- add typing for some functions
- remove unused import in `utils/file-utils.ts`
=> add typings 

lib/utils/atomical-operation-builder.ts, lib/utils/miner-worker.ts
Great News!
[Neutron has arrived to this open source community!](https://www.atomicalneutron.com/)
We are excited to bring you the 10x speed boost about POW minting: 
Use sequence to compute Bitwork instead of always changing nonce and time.
=> [Neutron Protocol]10x speed boost POW: Use sequence to calculate Bitwork

lib/utils/atomical-operation-builder.ts, lib/utils/miner-worker.ts
We have improved the mining log such that we can visualize the POW progress!
Brought to you by Neutron:
=> [Visibility] Improve multithread mining log

lib/utils/atomical-operation-builder.ts, lib/utils/miner-worker.ts
Do not use random nonce and only use time to marble reveal addresses
=> [Neutron] Recoverable Reveal Addresses

lib/utils/atomical-operation-builder.ts
Update atomical-operation-builder.ts
=> Print revealTx.toHex only when the correct revealTx is found

lib/utils/atomical-operation-builder.ts
- Fixes https://github.com/atomicals/atomicals-js/issues/194
- Resolves https://github.com/atomicals-community/atomicals-guide/pull/2
=> 🐛 Escape from workers if no commit required

lib/utils/atomical-operation-builder.ts
Fixed the problem of fee inconsistency in the second broadcast.
=> Fix the problem of different Reveal gas fees caused by using bitwork

lib/utils/atomical-operation-builder.ts
Fixed the problem that the previous version could not compile after resolving conflicting codes.
=> Fixed the problem that the previous version could not compile after resolving conflicting codes.

lib/commands/set-container-dmint-interactive-command.ts
The previous implementation didn't check outputs and provided fewer details.
=> 🔒️ Enforce more strict check to DMint config

lib/cli.ts, lib/commands/get-container-item-validated-by-manifest-command.ts, lib/index.ts, lib/interfaces/api.interface.ts
=> ✨ Allow to validate DMint items with/without checking sealed container

lib/utils/atomical-operation-builder.ts
Improvement continues from #252.
FYI @shiralwz
=> 🚸 Retry when no valid input for excessive fees prompt
